### ISSUE TITLE
Add Value: Daily heads-up of trends

### ISSUE THREAD

**Issue by C-M-P-C** [cudeso/proof-value-cti#4]
# Daily heads-up of trends

---

The importance of choosing trustworthy information sources is highlighted by a daily heads-up of trends that also serves as a notification of significant cybersecurity upgrades. Considering how quickly cyber threats are evolving, we may stay up to date on new strategies, vulnerabilities, and signs of compromise by selecting reliable and accurate sources. In order to maintain a proactive security posture, it is crucial to rely on reliable intelligence feeds, information that could be provided by government, private companies or open-source.

---

## Source of intel

Government:
- [CISA](https://www.cisa.gov/about/contact-us/subscribe-updates-cisa)

Private companies:
- [MITRE](https://attack.mitre.org/)

Open-Source:
- [MISP](https://www.misp-project.org/)

**Comment by C-M-P-C** [comment]
Hi,

I love your initiative and i wanted to help you, if you think the text is good enough, you can post it.

**Comment by cudeso** [comment]
Awesome! Thanks for contributing. Added it via https://github.com/cudeso/proof-value-cti/commit/39d53b25d2392db5384d8fe8cd51215d0c83a076
